main:
  - name: Programa
    url: /programa/
    weight: 1
  - name: Planificaci√≥n
    url: /schedule/
    weight: 2
  - name: Clases
    url: /class/
    weight: 3
  - name: Trabajos
    url: /trabajos/
    weight: 4
  - name: Links
    url: /reference/
    weight: 5
